project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/notebooks/*.*"
    - "!.ipynb_checkpoints/"  # exclude ipynb checkpoints
    - "!*/.ipynb_checkpoints/" # exclude in subdirectories
    - "!.DS_Store"
    - "!*/.DS_Store"

website:
  title: "Teaching AI-Assisted Financial Analysis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/finance-with-ai
    background: dark
    search: true
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Kerry Back"

format:
  html:
    theme:
      light: flatly
      dark: superhero
    toc: true

execute:
  freeze: auto

comments:
  giscus:
    repo: finance-with-ai/blog
    repo-id: R_kgDOOkPrbQ
    category: General
    category-id: DIC_kwDOOkPrbc4Cpylb
    mapping: pathname
    reactions-enabled: true
    loading: lazy
    input-position: bottom
    theme: preferred_color_scheme 