project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/assets/*.*"
    - "!/notebooks/*.*"
    - "!/forthcoming/*.*"
    - "!.ipynb_checkpoints/"  # exclude ipynb checkpoints
    - "!*/.ipynb_checkpoints/" # exclude in subdirectories
    - "!.DS_Store"
    - "!*/.DS_Store"

site:
  title: "Teaching Finance with AI"
  site-url: https://finance-with-ai.org
  feed:
    type: rss2
  description: "Teaching the use of generative AI in finance"


  navbar:
    title: ""
    logo: "teaching_finance_with_ai_logo.png"
    background: primary
    right:
      - text: "About"
        href: about.qmd
      - text: "Subscribe"
        href: subscribe.qmd
      - text: Course Materials
        href: https://mgmt675-2025.kerryback.com
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Kerry Back"

format:
  html:
    theme:
      light: flatly
      dark: superhero
      
      
    css: styles.css
    toc: true

execute:
  freeze: auto

comments:
  giscus:
    repo: finance-with-ai/blog
    repo-id: R_kgDOOkPrbQ
    category: General
    category-id: DIC_kwDOOkPrbc4Cpylb
    mapping: pathname
    reactions-enabled: true
    loading: lazy
    input-position: bottom
    theme: preferred_color_scheme 




 